# Generated by Django 5.0 on 2023-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_restaurant_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='shipping_time',
            field=models.IntegerField(),
        ),
    ]
