# Generated by Django 5.0 on 2023-12-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_share',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='Order - 23456', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_share',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAPERING', 'PAPERING'), ('SENDING', 'SENDING'), ('CANCEL', 'CANCEL')], default='PAPERING', max_length=50),
        ),
    ]
