# Generated by Django 5.0 on 2023-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionorder',
            old_name='shipping_cost',
            new_name='shipping_cost_admin',
        ),
        migrations.AddField(
            model_name='transactionorder',
            name='shipping_cost_restaurant',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
